version: "3.8"

services:
  book-api-server:
    build: ./book-api-server
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    restart: always

  book-client:
    build: ./book-client
    ports:
      - "5001:5001"
    environment:
      - BOOK_API_URL=http://book-api-server:5000/books/search
    depends_on:
      - book-api-server
    restart: always
