name: CI/CD for Book API Server

on:
  push:
    paths:
      - 'book-api-server/**'
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PAT: ${{ secrets.PAT }}  # Personal Access Token
  GHCR_USER: ${{ github.repository_owner }}  # Repo owner

jobs:
  build-and-push-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.PAT }}" | docker login ghcr.io -u $GHCR_USER --password-stdin

      - name: Build and Push API Server
        run: |
          cd book-api-server
          REPO_NAME=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker buildx build --platform linux/amd64 -t ghcr.io/$REPO_NAME/book-api-server:latest --push .

  # deploy-api:
  #   runs-on: ubuntu-latest
  #   needs: build-and-push-api

  #   steps:
  #     - name: Log in to Azure
  #       run: |
  #         az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

  #     - name: Deploy API Server to Azure
  #       run: |
  #         REPO_NAME=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
  #         az container create --resource-group myResourceGroup --name book-api-server \
  #           --image ghcr.io/$REPO_NAME/book-api-server:latest --cpu 1 --memory 1 \
  #           --registry-login-server ghcr.io --registry-username $GHCR_USER --registry-password ${{ secrets.PAT }} \
  #           --dns-name-label book-api-server --ports 5000
